#!/usr/bin/env node

/**
 * Bumps the build number in app.json (Android versionCode / iOS buildNumber)
 * before a release build, and optionally sets the version name (expo.version)
 * if a build name is provided.
 *
 * The native android/ and ios/ folders are generated by `expo prebuild`, so
 * app.json is the single source of truth for versions. All environments
 * (stage / preprod / production) share the same app.json, so there is no
 * per-environment target to pick.
 *
 * Usage:
 *   node scripts/bump-version.js <android|ios|all> [buildName]
 */

const path = require('path');
const fs = require('fs');

const APP_JSON_PATH = path.join(__dirname, '../app.json');
const PLATFORMS = ['android', 'ios', 'all'];
const BUILD_NAME_REGEX = /^\d+\.\d+\.\d+$/;

const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
};

function colorLog(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function readAppJson() {
  return JSON.parse(fs.readFileSync(APP_JSON_PATH, 'utf8'));
}

function writeAppJson(config) {
  fs.writeFileSync(APP_JSON_PATH, `${JSON.stringify(config, null, 2)}\n`);
}

// ---- Android (expo.android.versionCode, a number) ----
function bumpAndroid(config) {
  const oldVersionCode = Number(config.expo.android.versionCode ?? 0);
  const newVersionCode = oldVersionCode + 1;
  config.expo.android.versionCode = newVersionCode;

  return {
    platform: 'android',
    oldBuild: oldVersionCode,
    newBuild: newVersionCode,
  };
}

// ---- iOS (expo.ios.buildNumber, a string) ----
function bumpIos(config) {
  const oldBuildNumber = Number(config.expo.ios.buildNumber ?? 0);
  const newBuildNumber = oldBuildNumber + 1;
  config.expo.ios.buildNumber = String(newBuildNumber);

  return {
    platform: 'ios',
    oldBuild: oldBuildNumber,
    newBuild: newBuildNumber,
  };
}

// expo.version is shared by both platforms (versionName / MARKETING_VERSION)
function bumpVersion(platform, buildName) {
  const config = readAppJson();
  const oldVersionName = config.expo.version;
  if (buildName) {
    config.expo.version = buildName;
  }

  const results = [];
  if (platform === 'android' || platform === 'all') {
    results.push(bumpAndroid(config));
  }
  if (platform === 'ios' || platform === 'all') {
    results.push(bumpIos(config));
  }

  writeAppJson(config);

  return { oldVersionName, newVersionName: config.expo.version, results };
}

function showUsage() {
  colorLog('📦 Version Bumper', 'blue');
  console.log('');
  console.log(
    'Usage: node scripts/bump-version.js <android|ios|all> [buildName]'
  );
  console.log('');
  console.log(
    '  buildName   Optional. Sets expo.version (Android versionName / iOS MARKETING_VERSION), e.g. 1.2.0.'
  );
  console.log('              If omitted, only the build number is bumped.');
}

if (require.main === module) {
  const [, , platformArg, buildNameArg] = process.argv;

  if (!platformArg || platformArg === '--help' || platformArg === '-h') {
    showUsage();
    process.exit(platformArg ? 0 : 1);
  }

  if (!PLATFORMS.includes(platformArg)) {
    colorLog(`❌ Invalid platform: ${platformArg}`, 'red');
    colorLog(`Available platforms: ${PLATFORMS.join(', ')}`, 'yellow');
    process.exit(1);
  }

  if (buildNameArg && !BUILD_NAME_REGEX.test(buildNameArg)) {
    colorLog(`❌ Invalid buildName: ${buildNameArg} (expected x.y.z)`, 'red');
    process.exit(1);
  }

  let summary;
  try {
    summary = bumpVersion(platformArg, buildNameArg);
  } catch (error) {
    colorLog(`❌ Version bump failed: ${error.message}`, 'red');
    process.exit(1);
  }

  colorLog('✅ Version bump complete:', 'green');
  colorLog(
    `   Version name: "${summary.oldVersionName}" → "${summary.newVersionName}"`,
    'cyan'
  );
  for (const r of summary.results) {
    const label =
      r.platform === 'android' ? 'Android versionCode' : 'iOS buildNumber';
    colorLog(`   ${label}: ${r.oldBuild} → ${r.newBuild}`, 'cyan');
  }
}

module.exports = { bumpVersion };
